### ISSUE TITLE
`AttributeError: module 'collections' has no attribute 'MutableMapping'` when using python 3.10

### ISSUE THREAD

**Issue by 3nt3** [ajitid/live-server#2]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.10/site-packages/livereload/__init__.py", line 15, in <module>
    from .server import Server, shell
  File "/usr/lib/python3.10/site-packages/livereload/server.py", line 20, in <module>
    from tornado.wsgi import WSGIContainer
  File "/home/ente/.local/lib/python3.10/site-packages/tornado/wsgi.py", line 40, in <module>
    from tornado import httputil
  File "/home/ente/.local/lib/python3.10/site-packages/tornado/httputil.py", line 107, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by ajitid** [comment]
Hello. I'm not actively maintaining this repo. But just by looking at the stack trace, I can see upgrading tornado would make this work.

I would happily take a pull request if you send one.
